version: '3.1'
services:
  tto-db:
    image: postgres:14-alpine
    container_name: tto-database
    environment:
      - POSTGRES_DB=tto
      - POSTGRES_USER=tto
      - POSTGRES_PASSWORD=tto
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/

  tto-game:
    build:
      context: ./tto-main
    container_name: tto-game
    ports:
      - "9090:8080"
    depends_on:
      - tto-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tto-db:5432/tto
      - SPRING_DATASOURCE_USERNAME=tto
      - SPRING_DATASOURCE_PASSWORD=tto
      - TTO_SESSION_ATTR_NAME=gameId
      - TTO_AI_SYMBOL=X
      - TTO_USER_SYMBOL=0
      - TTO_API_ENDPOINT=v1
      - SPRING_JPA_SHOW_SQL=false
      - BOT_TOKEN=