###
POST http://localhost:9090/v1/?userStart=true&gameLevel=HARD

###
PATCH http://localhost:9090/v1/0
###
PATCH http://localhost:9090/v1/1
###
PATCH http://localhost:9090/v1/2
###
PATCH http://localhost:9090/v1/3
###
PATCH http://localhost:9090/v1/4
###
PATCH http://localhost:9090/v1/5
###
PATCH http://localhost:9090/v1/6
###
PATCH http://localhost:9090/v1/7
###
PATCH http://localhost:9090/v1/8

###
### 0 1 2
### 3 4 5
### 6 7 8

###
GET http://localhost:9090/v1/board

###
PATCH http://localhost:9090/v1/cancelStep

###
