###
POST http://localhost:9090/v1/?userStart=false&gameLevel=HARD

###
PATCH http://localhost:9090/v1/1

###
### 0 1 2
### 3 4 5
### 6 7 8

###
GET http://localhost:9090/v1/board

###
PATCH http://localhost:9090/v1/cancelStep

###
